name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start services
      run: docker-compose up -d --build

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..20}; do
          if docker-compose exec -T db pg_isready -h db -p 5432; then
            echo "Postgres is ready!"
            exit 0
          fi
          echo "Waiting for Postgres... retry $i"
          sleep 5
        done
        echo "Postgres failed to start."
        exit 1

    - name: Run tests
      run: docker-compose exec -T web pytest

    - name: Stop services
      run: docker-compose down
